INSERT INTO music (name) VALUES ( 'Bohemian Rhapsody'),
       ('Stairway to Heaven'),
       ('Imagine'),
       ('Sweet Child O Mine'),
       ('Hey Jude'),
       ('Hotel California'),
       ('Billie Jean'),
       ('Wonderwall'),
       ('Smells Like Teen Spirit'),
       ('Let It Be'),
       ('I Want It All'),
       ('November Rain'),
       ('Losing My Religion'),
       ('One'),
       ('With or Without You'),
       ('Sweet Caroline'),
       ('Yesterday'),
       ('Dont Stop Believin'),
       ('Crazy Train'),
       ('Always');